# Generated by Django 2.1.5 on 2021-11-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogpark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
