# Generated by Django 2.1.5 on 2021-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogpark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='num_dogs',
            field=models.IntegerField(blank=True),
        ),
    ]
