# Generated by Django 2.1.5 on 2021-10-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogpark', '0002_auto_20211021_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='num_dogs',
        ),
        migrations.AddField(
            model_name='dog',
            name='num_dogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
