# Generated by Django 2.1.5 on 2021-10-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogpark', '0003_auto_20211021_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='num_dogs',
        ),
        migrations.AddField(
            model_name='owner',
            name='num_dogs',
            field=models.IntegerField(default=0),
        ),
    ]
