# Generated by Django 2.1.5 on 2021-10-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogpark', '0007_auto_20211028_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='addGoal',
            new_name='add_goal',
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='completeGoal',
            new_name='complete_goal',
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='pointsEarned',
            new_name='points_earned',
        ),
    ]
